<?php
require_once __DIR__ . '/includes/auth_check.php';
include __DIR__ . '/header.php';
?>

<main id="app">
    <div class="container mx-auto px-4 py-8">
        <div id="map-selection" class="mb-6">
            <div class="flex items-center justify-between mb-4">
                <h1 class="text-3xl font-bold text-white">Network Map</h1>
                <div class="flex gap-4">
                    <select id="mapSelector" class="bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white"></select>
                    <button id="newMapBtn" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700"><i class="fas fa-plus mr-2"></i>New Map</button>
                    <button id="renameMapBtn" class="px-4 py-2 bg-yellow-600/80 text-white rounded-lg hover:bg-yellow-700"><i class="fas fa-edit mr-2"></i>Rename Map</button>
                    <button id="deleteMapBtn" class="px-4 py-2 bg-red-600/80 text-white rounded-lg hover:bg-red-700"><i class="fas fa-trash mr-2"></i>Delete Map</button>
                </div>
            </div>
        </div>

        <div id="map-container" class="hidden">
            <div id="map-controls" class="bg-slate-800 border border-slate-700 rounded-lg shadow-xl p-4 mb-6">
                <div class="flex items-center justify-between">
                    <h2 id="currentMapName" class="text-xl font-semibold text-white"></h2>
                    <div class="flex items-center gap-2">
                        <button id="scanNetworkBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Scan Network"><i class="fas fa-search"></i></button>
                        <button id="refreshStatusBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Refresh Device Statuses"><i class="fas fa-sync-alt"></i></button>
                        
                        <div class="flex items-center space-x-2 pl-2 ml-2 border-l border-slate-700">
                            <label for="liveRefreshToggle" class="text-sm text-slate-400 select-none cursor-pointer">Live Status</label>
                            <label class="relative inline-flex items-center cursor-pointer">
                                <input type="checkbox" id="liveRefreshToggle" class="sr-only peer">
                                <div class="w-11 h-6 bg-slate-600 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-cyan-600"></div>
                            </label>
                        </div>

                        <div class="pl-2 ml-2 border-l border-slate-700 flex items-center gap-2">
                            <button id="placeDeviceBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Place Existing Device"><i class="fas fa-download"></i></button>
                            <button id="addDeviceBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Add New Device"><i class="fas fa-plus"></i></button>
                            <button id="addEdgeBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Add Connection"><i class="fas fa-project-diagram"></i></button>
                            <button id="exportBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Export Map"><i class="fas fa-file-export"></i></button>
                            <button id="importBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Import Map"><i class="fas fa-file-import"></i></button>
                            <input type="file" id="importFile" class="hidden" accept=".json">
                            <button id="mapSettingsBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Map Settings"><i class="fas fa-cog"></i></button>
                            <button id="fullscreenBtn" class="px-3 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600" title="Toggle Fullscreen"><i class="fas fa-expand"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <div id="network-map-wrapper">
                <div id="network-map"></div>
                <div id="context-menu" class="context-menu"></div>
                <div id="status-legend">
                    <!-- Legend items are now generated by map.js -->
                </div>
            </div>
        </div>
        
        <div id="no-maps" class="text-center py-16 bg-slate-800 border border-slate-700 rounded-lg hidden">
            <i class="fas fa-map-signs text-slate-600 text-5xl mb-4"></i>
            <h2 class="text-2xl font-bold text-white mb-2">No Network Maps Found</h2>
            <p class="text-slate-400 mb-6">Create a map to start visualizing your network.</p>
            <button id="createFirstMapBtn" class="px-6 py-3 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700 text-lg">Create Your First Map</button>
        </div>
    </div>

    <!-- Modals -->
    <div id="deviceModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-md max-h-[90vh] overflow-y-auto">
            <h2 id="modalTitle" class="text-xl font-semibold text-white mb-4">Add Device</h2>
            <form id="deviceForm" class="space-y-6">
                <input type="hidden" id="deviceId" name="id">
                
                <!-- Basic Information -->
                <fieldset class="border border-slate-700 rounded-lg p-4 space-y-4">
                    <legend class="text-sm font-medium text-slate-400 px-2">Basic Information</legend>
                    <div>
                        <label for="deviceName" class="block text-sm font-medium text-slate-400 mb-1">Name</label>
                        <input type="text" id="deviceName" name="name" placeholder="Device Name" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white" required>
                    </div>
                    <div>
                        <label for="deviceType" class="block text-sm font-medium text-slate-400 mb-1">Type (Default Icon)</label>
                        <select id="deviceType" name="type" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                            <option value="box">Box (Group)</option>
                            <option value="camera">CC Camera</option>
                            <option value="cloud">Cloud</option>
                            <option value="database">Database</option>
                            <option value="firewall">Firewall</option>
                            <option value="ipphone">IP Phone</option>
                            <option value="laptop">Laptop/PC</option>
                            <option value="mobile">Mobile Phone</option>
                            <option value="nas">NAS</option>
                            <option value="rack">Networking Rack</option>
                            <option value="printer">Printer</option>
                            <option value="punchdevice">Punch Device</option>
                            <option value="radio-tower">Radio Tower</option>
                            <option value="router">Router</option>
                            <option value="server">Server</option>
                            <option value="switch">Switch</option>
                            <option value="tablet">Tablet</option>
                            <option value="wifi-router">WiFi Router</option>
                            <option value="other">Other</option>
                        </select>
                    </div>
                    <div>
                        <label for="deviceDescription" class="block text-sm font-medium text-slate-400 mb-1">Description</label>
                        <textarea id="deviceDescription" name="description" rows="2" placeholder="Optional notes about the device" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white"></textarea>
                    </div>
                </fieldset>

                <!-- Network Configuration (Conditional) -->
                <fieldset id="networkConfigWrapper" class="border border-slate-700 rounded-lg p-4 space-y-4">
                    <legend class="text-sm font-medium text-slate-400 px-2">Network Configuration</legend>
                    <div id="deviceIpWrapper">
                        <label for="deviceIp" class="block text-sm font-medium text-slate-400 mb-1">IP Address</label>
                        <input type="text" id="deviceIp" name="ip" placeholder="IP Address" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                    </div>
                    <div id="devicePortWrapper">
                        <label for="checkPort" class="block text-sm font-medium text-slate-400 mb-1">Service Port (Optional)</label>
                        <input type="number" id="checkPort" name="check_port" placeholder="e.g., 80 for HTTP" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                        <p class="text-xs text-slate-500 mt-1">If set, status is based on this port. If empty, it will use ICMP (ping).</p>
                    </div>
                    <div id="pingIntervalWrapper">
                        <label for="pingInterval" class="block text-sm font-medium text-slate-400 mb-1">Ping Interval (seconds)</label>
                        <input type="number" id="pingInterval" name="ping_interval" placeholder="e.g., 60 (optional)" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                        <p class="text-xs text-slate-500 mt-1">Set to 0 or leave blank to disable auto-ping.</p>
                    </div>
                </fieldset>

                <!-- Appearance Settings -->
                <fieldset class="border border-slate-700 rounded-lg p-4 space-y-4">
                    <legend class="text-sm font-medium text-slate-400 px-2">Appearance</legend>
                    <div>
                        <label for="deviceMap" class="block text-sm font-medium text-slate-400 mb-1">Map Assignment</label>
                        <select id="deviceMap" name="map_id" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                            <!-- Populated by JS -->
                        </select>
                    </div>
                    <div>
                        <label id="iconSizeLabel" for="iconSize" class="block text-sm font-medium text-slate-400 mb-1">Icon Size</label>
                        <input type="number" id="iconSize" name="icon_size" placeholder="e.g., 50" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                    </div>
                    <div>
                        <label id="nameTextSizeLabel" for="nameTextSize" class="block text-sm font-medium text-slate-400 mb-1">Name Text Size</label>
                        <input type="number" id="nameTextSize" name="name_text_size" placeholder="e.g., 14" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                    </div>
                    <div id="showLivePingWrapper">
                        <label for="showLivePing" class="flex items-center text-sm font-medium text-slate-400">
                            <input type="checkbox" id="showLivePing" name="show_live_ping" class="h-4 w-4 rounded border-slate-500 bg-slate-700 text-cyan-600 focus:ring-cyan-500">
                            <span class="ml-2">Show live ping status on map</span>
                        </label>
                    </div>
                    <fieldset class="border border-slate-600 rounded-lg p-4">
                        <legend class="text-sm font-medium text-slate-400 px-2">Custom Icon</legend>
                        <div class="space-y-3">
                            <div>
                                <label for="icon_url" class="block text-sm font-medium text-slate-400 mb-1">Icon URL</label>
                                <input type="text" id="icon_url" name="icon_url" placeholder="Leave blank to use default icon" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-sm text-white">
                            </div>
                            <div class="text-center text-slate-500 text-sm">OR</div>
                            <div>
                                <label for="icon_upload" class="block text-sm font-medium text-slate-400 mb-1">Upload Icon</label>
                                <input type="file" id="icon_upload" name="icon_upload" accept="image/*" class="w-full text-sm text-slate-400 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-cyan-600/20 file:text-cyan-300 hover:file:bg-cyan-600/40">
                                <div id="icon_upload_loader" class="hidden mt-2"><div class="loader inline-block w-4 h-4"></div><span class="ml-2 text-sm">Uploading...</span></div>
                                <p class="text-xs text-slate-500 mt-1">Upload requires the item to be saved first.</p>
                            </div>
                            <div id="icon_preview_wrapper" class="hidden mt-2 text-center">
                                <img id="icon_preview" src="" alt="Icon Preview" class="max-w-full h-16 mx-auto bg-slate-700 p-1 rounded">
                            </div>
                        </div>
                    </fieldset>
                </fieldset>

                <!-- Status Thresholds (Conditional) -->
                <fieldset id="thresholdsWrapper" class="border border-slate-700 rounded-lg p-4 space-y-4">
                    <legend class="text-sm font-medium text-slate-400 px-2">Status Thresholds (Optional)</legend>
                    <p class="text-sm text-slate-500">Define values to trigger 'Warning' or 'Critical' status.</p>
                    <div class="grid grid-cols-2 gap-4">
                        <div>
                            <label for="warning_latency_threshold" class="block text-xs text-slate-400 mb-1">Warn Latency (ms)</label>
                            <input type="number" id="warning_latency_threshold" name="warning_latency_threshold" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-sm text-white">
                        </div>
                        <div>
                            <label for="warning_packetloss_threshold" class="block text-xs text-slate-400 mb-1">Warn Packet Loss (%)</label>
                            <input type="number" id="warning_packetloss_threshold" name="warning_packetloss_threshold" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-sm text-white">
                        </div>
                        <div>
                            <label for="critical_latency_threshold" class="block text-xs text-slate-400 mb-1">Critical Latency (ms)</label>
                            <input type="number" id="critical_latency_threshold" name="critical_latency_threshold" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-sm text-white">
                        </div>
                        <div>
                            <label for="critical_packetloss_threshold" class="block text-xs text-slate-400 mb-1">Critical Packet Loss (%)</label>
                            <input type="number" id="critical_packetloss_threshold" name="critical_packetloss_threshold" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-sm text-white">
                        </div>
                    </div>
                </fieldset>

                <div class="flex justify-end gap-4 mt-6">
                    <button type="button" id="cancelBtn" class="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600">Cancel</button>
                    <button type="submit" id="saveBtn" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700">Save</button>
                </div>
            </form>
        </div>
    </div>

    <div id="edgeModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-sm">
            <h2 class="text-xl font-semibold text-white mb-4">Edit Connection</h2>
            <form id="edgeForm">
                <input type="hidden" id="edgeId">
                <select id="connectionType" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                    <option value="cat5">CAT5 Cable</option><option value="fiber">Fiber Optic</option><option value="wifi">WiFi</option><option value="radio">Radio</option>
                </select>
                <div class="flex justify-end gap-4 mt-6">
                    <button type="button" id="cancelEdgeBtn" class="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600">Cancel</button>
                    <button type="submit" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700">Save</button>
                </div>
            </form>
        </div>
    </div>

    <div id="scanModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-2xl border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-xl font-semibold text-white">Scan Network for Devices</h2>
                <button id="closeScanModal" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <div class="bg-slate-900/50 p-4 rounded-lg border border-slate-700 mb-4">
                <form id="scanForm" class="flex flex-col sm:flex-row gap-4">
                    <input type="text" id="subnetInput" placeholder="e.g., 192.168.1.0/24" value="192.168.1.0/24" class="flex-1 bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                    <button type="submit" id="startScanBtn" class="px-6 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700">
                        <i class="fas fa-search mr-2"></i>Start Scan
                    </button>
                </form>
            </div>
            <div id="scanResultWrapper" class="max-h-96 overflow-y-auto">
                <div id="scanLoader" class="text-center py-8 hidden"><div class="loader mx-auto"></div><p class="mt-2 text-slate-400">Scanning... this may take a moment.</p></div>
                <div id="scanResults"></div>
                <div id="scanInitialMessage" class="text-center py-8 text-slate-500">
                    <i class="fas fa-network-wired text-4xl mb-4"></i>
                    <p>Enter a subnet and start the scan to discover devices.</p>
                    <p class="text-sm mt-2">(Requires <a href="https://nmap.org/" target="_blank" class="text-cyan-400 hover:underline">nmap</a> to be installed on the server)</p>
                </div>
            </div>
        </div>
    </div>

    <div id="mapSettingsModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-lg border border-slate-700">
            <h2 class="text-xl font-semibold text-white mb-4">Map Appearance Settings</h2>
            <form id="mapSettingsForm">
                <div class="space-y-4">
                    <div>
                        <label for="mapBgColor" class="block text-sm font-medium text-slate-400 mb-1">Background Color</label>
                        <div class="flex items-center gap-2">
                            <input type="color" id="mapBgColor" name="background_color" class="p-1 h-10 w-14 block bg-slate-900 border border-slate-600 cursor-pointer rounded-lg" value="#1e293b">
                            <input type="text" id="mapBgColorHex" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                        </div>
                    </div>
                    <div>
                        <label for="mapBgImageUrl" class="block text-sm font-medium text-slate-400 mb-1">Background Image URL</label>
                        <input type="text" id="mapBgImageUrl" name="background_image_url" placeholder="Leave blank for no image" class="w-full bg-slate-900 border border-slate-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-cyan-500 text-white">
                    </div>
                    <div class="text-center text-slate-500 text-sm">OR</div>
                    <div>
                        <label for="mapBgUpload" class="block text-sm font-medium text-slate-400 mb-1">Upload Background Image</label>
                        <input type="file" id="mapBgUpload" accept="image/*" class="w-full text-sm text-slate-400 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-cyan-600/20 file:text-cyan-300 hover:file:bg-cyan-600/40">
                        <div id="mapBgUploadLoader" class="hidden mt-2"><div class="loader inline-block w-4 h-4"></div><span class="ml-2 text-sm">Uploading...</span></div>
                    </div>
                </div>
                <div class="flex justify-between items-center mt-6">
                    <button type="button" id="resetMapBgBtn" class="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600">Reset to Default</button>
                    <div>
                        <button type="button" id="cancelMapSettingsBtn" class="px-4 py-2 bg-slate-600 text-slate-300 rounded-lg hover:bg-slate-500 mr-2">Close</button>
                        <button type="submit" class="px-4 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700">Save Changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
    <!-- Place Device Modal -->
    <div id="placeDeviceModal" class="modal-backdrop hidden">
        <div class="modal-panel bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-lg border border-slate-700">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-xl font-semibold text-white">Place an Existing Device</h2>
                <button id="closePlaceDeviceModal" class="text-slate-400 hover:text-white text-2xl">&times;</button>
            </div>
            <div id="placeDeviceList" class="max-h-96 overflow-y-auto">
                <!-- Unmapped devices will be listed here -->
            </div>
            <div id="placeDeviceLoader" class="text-center py-8 hidden"><div class="loader mx-auto"></div></div>
        </div>
    </div>
</main>

<?php include __DIR__ . '/footer.php'; ?>